export { default as HomePage } from './HomePage'
export { default as ProjectPage } from './ProjectPage'
export { default as AboutPage } from './AboutPage'
export { default as ContactPage } from './ContactPage'
export { default as ProjectsPage } from './ProjectsPage'
